apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus
  namespace: monitoring    # Use the "monitoring" namespace or any namespace you prefer
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest    # Prometheus image
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"     # Configuration file path
          - "--storage.tsdb.path=/prometheus"                 # Storage path for TSDB
          - "--web.listen-address=:9090"                      # Prometheus server listening port
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config         # ConfigMap for Prometheus configuration
      - name: prometheus-data
        emptyDir: {}                      # Data directory volume for Prometheus storage
--- 
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: NodePort    # Exposes the service on each node’s IP at a static port
  selector:
    app: prometheus # Matches the label defined in the DaemonSet
  ports:
    - port: 80             # Port to expose the service on (external)
      targetPort: 9090     # Port that the Prometheus container is listening on
      nodePort: 30090      # Static port on which the service will be exposed
      protocol: TCP
