apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: dev
spec:
  hard:
    pods: "10"                        # Maximum of 10 pods in the namespace
    requests.cpu: "4"                 # Maximum total of 4 CPUs requested across all pods
    requests.memory: "8Gi"            # Maximum total of 8 GiB of memory requested across all pods
    limits.cpu: "8"                   # Maximum total of 8 CPUs limit across all pods
    limits.memory: "16Gi"             # Maximum total of 16 GiB of memory limit across all pods
    persistentvolumeclaims: "5"       # Maximum of 5 PersistentVolumeClaims in the namespace
    services: "5"                     # Maximum of 5 Services in the namespace
    configmaps: "10"                  # Maximum of 10 ConfigMaps in the namespace
    secrets: "10"                     # Maximum of 10 Secrets in the namespace
    replicationcontrollers: "5"       # Maximum of 5 ReplicationControllers in the namespace
    resourcequotas: "1"               # Maximum of 1 ResourceQuota object in the namespace
